log_dir: "Checkpoint"
save_freq: 10
device: "cuda"
epochs: 200
batch_size: 32
pretrained_model: ""
train_data: "Data/yue_train.txt"
val_data: "Data/yue_val.txt"
language: "yue"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
  input_dim: 80
  hidden_dim: 256
  n_token: 1742
  token_embedding_dim: 512

optimizer_params:
  lr: 0.0005
